version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testovoe-api
    ports:
      - "7002:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=localhost,back
    command: sh -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '7003:5432'
    volumes:
      - db_postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always


volumes:
  db_postgres: