# Generated by Django 4.2.2 on 2023-07-10 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('credit_request_id', models.AutoField(db_column='credit_request_id', primary_key=True, serialize=False)),
                ('credit_request_num', models.IntegerField(db_column='credit_request_num')),
                ('info', models.TextField(null=True)),
                ('name_owner', models.TextField(db_column='name_owner')),
                ('surname_owner', models.TextField(db_column='surname_owner')),
                ('create_date', models.DateTimeField(db_column='create_date', default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'credit_request',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('product_name', models.TextField(db_column='product_name')),
                ('info', models.TextField(null=True)),
                ('inv_num', models.CharField(db_column='inv_num')),
                ('create_date', models.DateTimeField(db_column='create_date', default=datetime.datetime.now)),
                ('credit_request_id', models.ForeignKey(db_column='credit_request_id', on_delete=django.db.models.deletion.RESTRICT, related_name='credit_pr', to='app.creditrequest')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(db_column='manufacturer_id', primary_key=True, serialize=False)),
                ('manufacturer_name', models.TextField(db_column='manufacturer_name')),
                ('info', models.TextField(null=True)),
                ('inv_num', models.CharField(db_column='inv_num')),
                ('create_date', models.DateTimeField(db_column='create_date', default=datetime.datetime.now)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.RESTRICT, related_name='product', to='app.product')),
            ],
            options={
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(db_column='contract_id', primary_key=True, serialize=False)),
                ('contract_num', models.IntegerField(db_column='contract_num')),
                ('info', models.TextField(null=True)),
                ('name_owner', models.TextField(db_column='name_owner')),
                ('surname_owner', models.TextField(db_column='surname_owner')),
                ('phone', models.TextField(null=True)),
                ('create_date', models.DateTimeField(db_column='create_date', default=datetime.datetime.now)),
                ('credit_request_id', models.ForeignKey(db_column='credit_request_id', on_delete=django.db.models.deletion.RESTRICT, related_name='credit', to='app.creditrequest')),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
